#!/bin/sh

echo_usage() {
    echo "Available arguments:\tdc\tdc_cdi\tlinux\n"
    echo "Usage:"
    echo "\t./build_face-off <argument>"
}

if [ $# -eq 0 ]; then
    echo "You must provide a platform as an argument!"
    echo_usage
    exit 1
fi

argument=$1

case "$argument" in
    clean)
        echo "Cleaning up...\n"
        make -f Makefile_dc clean
        make -f Makefile_linux clean
        ;;
    dc)
        echo "Building for DreamCast...\n"
        source $KOS_BASE/environ.sh
        make -f Makefile_dc
        #mkdcdisc -e face-off.elf -o face-off.cdi
        ;;
    dc_cdi)
        echo "Building DreamCast disc...\n"
        mkdcdisc -e face-off.elf -o face-off.cdi
        ;;
    linux)
        echo "Building for Linux...\n"
        make -f Makefile_linux
        ;;
    *)
        echo "Malformed argument!"
        echo_usage
        ;;
esac
